env:
  contexts:
  - name: Authentication Test
    urls:
    - ${ZURL}
    includePaths:
    - ${ZURL}.*
    authentication:
      method: browser
      parameters:
        loginPageUrl: ${ZLOGIN}
        loginPageWait: 2
        browserId: firefox-headless
      verification:
        method: autodetect
    sessionManagement:
      method: autodetect
    users:
    - name: testuser
      credentials:
        password: ${ZPASS}
        username: ${ZUSER}
jobs:
- type: requestor
  parameters:
    user: testuser
  requests:
  - name: Get Account Details
    url: ${ZURL}/bank/showAccount?listAccounts=800002
    method: GET
    responseCode: 200

