env:
  contexts:
  - name: Authentication Test
    urls:
    - http://testfire.net
    includePaths:
    - https?://testfire.net.*
    authentication:
      method: browser
      parameters:
        loginPageUrl: http://testfire.net/login.jsp
        loginPageWait: 2
        browserId: firefox-headless
        steps:
        - description: Fill Username
          type: USERNAME
          cssSelector: "#uid"
          value: jsmith
          timeout: 1000
      verification:
        method: autodetect
    sessionManagement:
      method: autodetect
    users:
    - name: testuser
      credentials:
        password: ${testfire_pass}
        username: ${testfire_user}
jobs:
- type: passiveScan-config
  parameters:
    disableAllRules: true
  rules:
  - name: Authentication Request Identified
    id: 10111
    threshold: medium
  - name: Session Management Response Identified
    id: 10112
    threshold: medium
  - name: Verification Request Identified
    id: 10113
    threshold: medium
- type: requestor
  parameters:
    user: testuser
  requests:
  - url: http://testfire.net
- type: passiveScan-wait
  parameters: {}
- name: auth-test-report
  type: report
  parameters:
    template: auth-report-json
    theme: null
    reportDir: .
    reportFile: auth-report.json
    reportTitle: ZAP by Checkmarx Scanning Report
  sections:
  - summary
  - afenv
  - statistics
