name: Run Auth Tests
on:
  workflow_dispatch:

jobs:
  publish:
    name: Authentication Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull nightly image
        run: docker pull ghcr.io/zaproxy/zaproxy:nightly
      - name: Authentication plan tests
        id: "test-auth-plans"
        if: ${{ ! cancelled() }}
        env:
          AUTH_SCANS_CREDS: ${{ secrets.AUTH_SCANS_CREDS }}
        run: |
          echo "$AUTH_SCANS_CREDS" | tee -a scans/auth/all_vars.env > /dev/null
          chmod -R a+w $(pwd)
          docker run --rm -v $(pwd):/zap/wrk/:rw --env-file scans/auth/all_vars.env -t zaproxy/zap-nightly /zap/wrk/scans/auth/auth_plan_tests.sh
          echo "\`\`\`yaml" >> $GITHUB_STEP_SUMMARY
          cat output/output.yml >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
      - name: Attach result
        uses: actions/upload-artifact@v4
        with:
         path: output/output.yml
